import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import ThemeRegistry from "../components/ThemeRegistry/ThemeRegistry";
import { Header } from "../components/layout/Header";
import { Footer } from "../components/layout/Footer";
import { BackgroundEffect } from "../components/ui/BackgroundEffect";
import "./globals.css";
import { Noto_Sans_JP, Noto_Serif_JP } from "next/font/google";
import localFont from "next/font/local"; // localFontをインポート

const notoSansJP = Noto_Sans_JP({
  subsets: ["latin"],
  variable: "--font-noto-sans-jp",
  weight: ["300", "400", "500", "700"],
  display: "swap",
});

const notoSerifJP = Noto_Serif_JP({
  subsets: ["latin"],
  variable: "--font-noto-serif-jp",
  weight: ["400", "600", "900"],
  display: "swap",
});

// せのびゴシックの設定 (ファイル配置が必要です)
const senobiGothic = localFont({
  src: [
    {
      path: "./fonts/Senobi-Gothic-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Senobi-Gothic-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    // Boldを900として代用
    {
      path: "./fonts/Senobi-Gothic-Bold.ttf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-senobi-gothic",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ja"
      className={`${notoSansJP.variable} ${notoSerifJP.variable} ${senobiGothic.variable}`}
    >
      {/* ...existing code... */}
      <body>
        <ThemeRegistry>
          <BackgroundEffect />
          <Header />
          {children}
          <Footer />
        </ThemeRegistry>
      </body>
    </html>
  );
}
